CREATE TABLE `orders` (
	`id` int AUTO_INCREMENT NOT NULL,
	`orderNo` varchar(100),
	`maker` varchar(64),
	`salesperson` varchar(64),
	`customer` varchar(128),
	`orderDate` varchar(20),
	`deliveryDate` varchar(20),
	`quantity` varchar(64),
	`orderDescription` text,
	`remarks` text,
	`topCover` text,
	`bottomCover` text,
	`plasticParts` text,
	`metalParts` text,
	`stickerSource` varchar(32),
	`stickerDesc` text,
	`stickerQty` text,
	`silkPrintDesc` text,
	`topLiner` text,
	`bottomLiner` text,
	`topLiner2` text,
	`bottomLiner2` text,
	`innerBox` text,
	`outerBox` text,
	`status` enum('draft','submitted','completed','cancelled') NOT NULL DEFAULT 'draft',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `orders_id` PRIMARY KEY(`id`)
);
