export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  // Company info for contracts / PI / CI
  companyCnName: process.env.COMPANY_CN_NAME ?? "",
  companyCnAddress: process.env.COMPANY_CN_ADDRESS ?? "",
  companyCnBankName: process.env.COMPANY_CN_BANK_NAME ?? "",
  companyCnBankAccount: process.env.COMPANY_CN_BANK_ACCOUNT ?? "",
  companyTaxNo: process.env.COMPANY_TAX_NO ?? "",
  companyEnName: process.env.COMPANY_EN_NAME ?? "",
  companyEnAddress: process.env.COMPANY_EN_ADDRESS ?? "",
  companyContactName: process.env.COMPANY_CONTACT_NAME ?? "",
  companyContactPhone: process.env.COMPANY_CONTACT_PHONE ?? "",
  companyContactEmail: process.env.COMPANY_CONTACT_EMAIL ?? "",
  companyIcbcEnBankName: process.env.COMPANY_ICBC_EN_BANK_NAME ?? "",
  companyIcbcUsdAccount: process.env.COMPANY_ICBC_USD_ACCOUNT ?? "",
  companyIcbcSwift: process.env.COMPANY_ICBC_SWIFT ?? "",
  companyCitiEnBankName: process.env.COMPANY_CITI_EN_BANK_NAME ?? "",
  companyCitiUsdAccount: process.env.COMPANY_CITI_USD_ACCOUNT ?? "",
  companyCitiSwift: process.env.COMPANY_CITI_SWIFT ?? "",
};
